### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by ka3de**
This PR adds the initial version for vulcan-metrics-client.

### CODE REVIEW

**Review by jesusfcr — COMMENTED** [review]
IMHO it would be nice to not to have to explicitly call NewDDClient, or at least to be able to leverage convention over configuration and use some standard environment variables:
DOGSTATSD_PORT DOGSTATSD_HOST,.... this model could be used to ease the use of the library and allow transparent use of other providers without even changing the client code, .... PROMETHEUS_PORT, PROMETHEUS_ENABLED...
Event the app could always call the function and let this library decide if the metrics should be sent or not based on the default variables DOGSTATSD_ENABLED.

I used this library https://pkg.go.dev/github.com/DataDog/datadog-lambda-go?tab=doc and it integrates very well, just by setting env variables, but you can override/provide the values if you want

**Comment by ka3de** [comment]
Thanks for your comments @jesusfcr, let's see if I understood what you meant.

So, regarding the explicit call to `NewDDClient`. For me this is not very problematic, as long as services using this library accept the interface as DI and not the concrete implementation it should be fine. For sure if you want to change the implementation (supposing we would support Prometheus for example) that will imply the modification of one line of code, Ok, that's true, but other options to avoid that have some considerations too.

For example, at first I was gonna create a factory method for the clients constructor so specific implementation constructors are not public, but I decided to not do it because then I have to tight the configuration options that the constructor needs, and that is not clear. For example, now for DD we need only the `statsdHost` and `statsdPort`, but what if prometheus client needs some other parameters? Then we can not use the same spec for the factory constructor, or we have to allow input parameters that might not be used depending on which implementation is requested, which I don't really like.

The only option possible that I see is to read from an ENV variable the implementation selected. E.g.: `METRICS_CLIENT_TYPE` {dd | prometheus} and then delegate on the specific type constructor TO ALSO READ FROM ENV VARS to retrieve its configuration, because otherwise we will stil tight the constructor to specific parameters. But the problem is that we usually use toml files instead of ENV vars..

So right now it's easy to use a factory method and hide the concrete implementation methods behind even for constructor, but if another implementation has to be created and it needs different parameters and we have to use toml config files for example, then we'll have to fix it somehow.

What do you think?
I'll try to make some modifications for this and push it so we can discuss.

**Comment by ka3de** [comment]
I added a factory constructor for the client with two different approaches, given input parameters or reading from ENV variables. I don't like the idea to have one single constructor which can read variables from both places and one has preference over the other etc, for me that's a little bit of a mess, but let me know what do you think.

With these changes we move the concrete implementation selection from code to configuration.
But, as I said, if a new implementation requires different config parameters (for example requires an API key) will have to create a new version for this library to not break backward compatibility, or delegate the parsing of these API key on the new implementation type to read it from environment.

**Comment by jesusfcr** [comment]
The idea was to make something transparent to the user, and not exclusive of one service, the client always access to the method the same way just **metrics.PushWithRate** and depending on the env variables metrics would decide what to do. It uses a singleton, you don't need to create multiple instances of the client, just one used everywhere.
In this sense, you don't need to decide which implementation to use METRICS_CLIENT_TYPE , you can use both at the same time. metrics would be an aggregator of metric services, the actual variables could be at the same time DD_* PROMETHEUS_*, .....
But don't worry, it was just an idea, probably doesn't worth doing that, or even is not possible.

**Comment by ka3de** [comment]
I see what you mean, but I don't know if I like that idea.
That way we would have to parse all the possible env variables for every execution and decide at runtime which service push metrics to, but usually you know which service push metrics to when you deploy the component so I don't know if it would be very used.

I agree though on the flexibility of the generic constructor and set the implementation type by configuration instead of code, so I think we got a good compromise now.

**Review by danfaizer — DISMISSED** [review]
👍

**Review by danfaizer — DISMISSED** [review]
👍

**Review by danfaizer — APPROVED** [review]
Like the renaming.
👍

**Pull request merged**
